# Created by: Juraj Lutter <juraj@lutter.sk>
# $FreeBSD$

PORTNAME=	zabbix50
CATEGORIES=	net-mgmt
PKGNAMESUFFIX=	-proxy

MASTERDIR=	${.CURDIR}/../zabbix50-server

OPTIONS_SINGLE_DB=	MYSQL PGSQL SQLITE ORACLE

.include "${MASTERDIR}/Makefile"
