# $FreeBSD$

PORTNAME=	zabbix50
CATEGORIES=	net-mgmt
PKGNAMESUFFIX=	-java

MASTERDIR=	${.CURDIR}/../zabbix50-server
PLIST=		${PKGDIR}/pkg-plist.java

OPTIONS_DEFINE=		IPV6

USE_JAVA=	yes

.include "${MASTERDIR}/Makefile"
